### ISSUE TITLE
Display moves to different locations despite being locked in place.

### ISSUE THREAD

**Issue by radhaz** [Hildaware/RideTheWind#1]
Zoning into new areas, logging in, and reloading can "randomly" cause the display to move to a new location despite being locked while using the ShestakUI. This happens about 3 out of 10 times (and always seemingly at the worst possible time really) and I can't recreate it consistently. The display ends up often off screen and I have to open options and slide the x/y around until I see on screen and then drag it in place and lock it again.

This is by the most aesthetically pleasing/useful addon for dragon racing that I've used but this random issue is making it unusable for the time being.

**Comment by bferrari352** [comment]
> Zoning into new areas, logging in, and reloading can "randomly" cause the display to move to a new location despite being locked while using the ShestakUI. This happens about 3 out of 10 times (and always seemingly at the worst possible time really) and I can't recreate it consistently. The display ends up often off screen and I have to open options and slide the x/y around until I see on screen and then drag it in place and lock it again.
> 
> This is by the most aesthetically pleasing/useful addon for dragon racing that I've used but this random issue is making it unusable for the time being.

That's super weird! Sorry I'm a bit late to getting a reply to this. Is this still an issue?

In regards to using a UI compilation... are you utilizing any kind of 'global scaling' within their configuration? My thoughts are some scaling it bumping UI widgets around?
